url: https://agiletourvienna.github.io

# Site settings
title: Agile Tour Vienna 2016
email: your-email@domain.com
description: "The Agile Tour Vienna is a non-profit event that aims at bringing together experts, practioners and everybody else who is interested in agile software development. The main conference language is German but we welcome talks in English and are looking forward to an exchange with international participants."

# Build settings
markdown: kramdown
permalink: pretty
